### PR TITLE
Add some work on operator << and a (very) general training function

### PR DESCRIPTION
**Pull request by Cypher1**
Happy to do some more work to get this up to scratch (I'm new to performance heavy c++).

I started work on a training function that takes a std::vector<std::pair<Matrix, Matrix>> which and a lambda (this is for defining your own end conditions) should make training simple.

I can add some documentation on how to use it you like it.

Thanks

### CODE REVIEW

**Comment by stagadish** [comment]
Hey,
Thank you for your contribution!

Can you please send me an example of how one would use your added functionality?
More specifically, the training function. Try to be as detailed as you can.

**Comment by Cypher1** [comment]
Sure thing:

Assuming we have a training set defined like so:

```
std::vector<std::pair<Matrix, Matrix> > trainingSet;
```

And a neural net:

```
NeuralNet net(input_nodes, layer_width, output_nodes, hidden_layers, learning_rate);
```

We can train the network via:

```
auto isTraining = [](auto &, auto &, int iterations) {return iterations < 100000;};
net.trainAll(trainingSet, isTraining);
```

Of course that lambda function (isTraining) returns a bool which is true (to continue) and false if we have finished. This could be inverted if you believe it is more intuitive.
The training function can also be modified so that it only evaluates the net every N iterations through the data and can use any measure to check that the network has 'passed'.
It can also be used to backup the current state of the network or print out the current progress.

e.g.

```
    net.trainAll(trainingSet, [](NeuralNet &self, const std::vector<std::pair<Matrix, Matrix>> &trainingSet, int iterations) {
            double failed = 1;
            double sigma = 0.01; // Maximum summed error
            if(iterations%10000 == 0) { // Check every 10,000 iterations
                double failed = 0;
                for(auto train : trainingSet) {
                    Matrix error = self.queryNet(train.first) - train.second;
                    for (auto i = 0U; i < error.getNumOfRows(); ++i) { // should be a faster way to do this
                        for (auto j = 0U; j < error.getNumOfCols(); ++j) {
                            failed += std::abs(error(i, j));
                        }
                    }
                }
                std::cout << "ITERATION " << iterations;
                std::cout << " Sum(E)" << failed << "\n";
                return failed > sigma; //keep going if error is too high
            }
            return true; // if we didn't check, keep going
        });
```

I'd love to create a default lambda (or a few defaults) which cover the main types of evaluation but I'm not sure what people use.
Cheers

**Comment by Cypher1** [comment]
Any chance these will get merged in? I'd love to do some more work on this but I might just fork it if you don't want to maintain it. Cheers

**Comment by stagadish** [comment]
Yes, there is a chance! The only issue is that I don't have time to review the changes right now. School is taking all my free time. I promise I will get to it as soon as I have a free moment, or the semester is over. Whichever comes first.

In the meantime (and if you cannot/will not wait), feel free to fork it and have fun with it. I'd love to hear how it performs in general.

Apologies!

**Comment by Cypher1** [comment]
Not at all. That's great to hear :)

I'll keep playing with it.
I have some ideas on how to tidy/speed it up.

Cheers.

**Comment by Cypher1** [comment]
Feel free to resurrect this at some point but I'm closing the PR for now

**Pull request closed without merging**
